--
--PROMPT CREANDO TABLA  ACTIVO
--
CREATE TABLE TB_ACTIVO (
  ID  NUMBER CONSTRAINT NN_TB_ACTIVO NOT NULL,
  SERIAL NUMBER,
  NOMBRE VARCHAR2(1000),
  DESCRIPCION VARCHAR2(1000),
  PESO NUMBER,
  ALTO NUMBER,
  ANCHO NUMBER,
  LARGO NUMBER,
  FECHA_COMPRA DATE,
  FECHA_BAJA  DATE,
  ID_TIPO NUMBER,
  ID_ESTADO NUMBER
);
